### ISSUE TITLE
Select helpers fail with column names containing `/`

### ISSUE THREAD

**Issue by etiennebacher** [nathaneastwood/poorman#105]
**Describe the bug**
Using select helpers like `everything()` doesn't work when column names are unusual, e.g when they contain `/`.

**To Reproduce**
``` r
test <- data.frame(
  `a/b` = 1,
  check.names = FALSE
)

# work
dplyr::select(test, dplyr::everything())
#>   a/b
#> 1   1
poorman::select(test, `a/b`)
#>   a/b
#> 1   1

# doesn't work
poorman::select(test, poorman::everything())
#> Error in switch(type, `:` = select_seq(x), `!` = select_negate(x), `-` = select_minus(x), : EXPR must be a length 1 vector
```

<sup>Created on 2022-08-02 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Expected behavior**
Should be able to select those columns containing unusual characters.

**System Information:**
Please detail the following information
- `R 4.2.0`
- `0.2.5.7`

**Additional context**
/

**Comment by nathaneastwood** [comment]
Interestingly, this is because of the use of `poorman::` since this works:

```r
library(poorman)
test <- data.frame(
  `a/b` = 1,
  check.names = FALSE
)
select(test, everything())
#   a/b
# 1   1
```
