### ISSUE TITLE
Implement if_else

### ISSUE THREAD

**Issue by msberends** [nathaneastwood/poorman#11]
Function `if_else()` misses from your impressive list of rewritten functions 😄 

To get started (still misses the `missing = NULL` argument of `dplyr::if_else()`):

```r
if_else <- function(condition, true, false, ...) {
  if (!is.logical(condition)) {
    stop("`condition` must be a logical vector")
  }

  if (!identical(class(true), class(false))) {
    stop("Classes of `true` and `false` differ")
  }

  ifelse(condition, true, false)
}
```

Thank you so much, this is an awesome package to not rely on `dplyr` anymore, GREAT for package developers.

**Comment by nathaneastwood** [comment]
Very kind words 😄 thanks! I’ll take a look at adding this in the coming days.
