### ISSUE TITLE
Add `slice_*()` family of functions

### ISSUE THREAD

**Issue by nathaneastwood** [nathaneastwood/poorman#22]
Implement

- [x]  `slice_head()`
- [x] `slice_tail()`
- [ ] `slice_min()`
- [ ] `slice_max()`
- [ ] `slice_sample()`

**Comment by AndreMikulec** [comment]
Any comment about a possible future integration of the new R 4.0.0 bquote splice ability?
```
The backquote function bquote() has a new argument splice to enable splicing a computed list of values into an expression, like ,@ in LISP's backquote.
```
from
CHANGES IN 4.0.0
https://cran.r-project.org/doc/manuals/r-devel/NEWS.html

**Comment by nathaneastwood** [comment]
I am still undecided about any R 4.0.0 specific code. To include it means users must depend on that version of R unless I start adding version checks into my code - which I really don't want to do. I think for now, I will be sticking with > R 3.4.x until more people are using 4.0.0.

As for this specific issue, can you give an example where you think it would be handy?

**Comment by AndreMikulec** [comment]
I think I wrote in error.  I will have to do some more research.
