### ISSUE TITLE
[BUG] Error of %>% operation

### ISSUE THREAD

**Issue by yzhlinscau** [nathaneastwood/poorman#26]
A simple example as following:

iris[,-5] %>% correlation::correlation() %>% summary

the %>% would work for iris[,-5] %>% correlation::correlation() , but not sucess for the next %>% summary. While dplyr do not have the problem. 

Error message as following: 
Error in rhs[[1L]] : object of type 'symbol' is not subsettable

**Comment by yzhlinscau** [comment]
when add '()' after function, then it works!
iris[,-5] %>% correlation::correlation() %>% summary()

**Comment by nathaneastwood** [comment]
Yeah exactly that. You need to include the `()` with the `{poorman}` pipe.
