### ISSUE TITLE
Rebrand?

### ISSUE THREAD

**Issue by kaneplusplus** [nathaneastwood/poorman#43]
I really like the design, readability, and implementation of this project. I think the adherence to minimal dependencies is great. But have you considered rebranding the package? I realize that the name is tongue in cheek but, at this point a considerable amount of work has been put in and it's beginning to look like a viable alternative to others. It looks to me more like a `baseplyr` package than a poor man's alternative.

**Comment by nathaneastwood** [comment]
I take your point on board @kaneplusplus :D the name is, admittedly very tongue in cheek. Hopefully the [Twitter poll](https://twitter.com/nathaneastwood_/status/1278761013094072322) will shed some light on other people's thoughts.

**Comment by kaneplusplus** [comment]
I think this is a great way to resolve this.

**Comment by nathaneastwood** [comment]
I think based on the poll results, comments and pms I’ve had, I’m going to keep the branding for now
