### ISSUE TITLE
[BUG] across() does not accept quoted fun/funcs.

### ISSUE THREAD

**Issue by Eyayaw** [nathaneastwood/poorman#56]
# `across()` does not accept quoted fun/funcs.

``` r
poorman::summarize(iris, poorman::across(c("Sepal.Length", "Sepal.Width"), list("mean", "sd", "median") ))
#> Error in funs[[j]](col, ...): attempt to apply non-function
```
``` r
dplyr::summarize(iris, dplyr::across(c("Sepal.Length", "Sepal.Width"), list("mean", "sd", "median")))
#>   Sepal.Length_1 Sepal.Length_2 Sepal.Length_3 Sepal.Width_1 Sepal.Width_2
#> 1       5.843333      0.8280661            5.8      3.057333     0.4358663
#>   Sepal.Width_3
#> 1             3
```

package version: Version: 0.2.3
R.version: R version 4.0.2 (2020-06-22)

Note: both poorman's and dplyr's across do not work when I supply a single quoted function. ```dplyr::summarize(iris, dplyr::across(c("Sepal.Length", "Sepal.Width"), "mean"))```

**Comment by nathaneastwood** [comment]
This has been handled in 8ce9fbf7468eef28ce12a48c9637a561f4f25f51
