### ISSUE TITLE
Add count() function

### ISSUE THREAD

**Issue by archymedes** [nathaneastwood/poorman#8]
First of all, thanks for your amazing work! I love the dependecy free philosophy. I'm going to use your package a lot, sure.
Have you considered to translate dplyr::count() function by one or more vaiables? 
After dplyr v0.7.0 it has the ability to return an ungrouped table, so it is very useful

**Comment by nathaneastwood** [comment]
Thanks for the encouragement :) I'm glad that it is going to be useful to people!
The plan is to continually add more and more features as I get time. I will work on `count()` next, however since you've requested it. :)

**Comment by nathaneastwood** [comment]
@archymedes I've added these functions now. Could you please give them a test?

**Comment by archymedes** [comment]
It's working perfectly!! Awesome job, thanks
