### ISSUE TITLE
Error with filter() when using lapply()

### ISSUE THREAD

**Issue by archymedes** [nathaneastwood/poorman#9]
The basic use of filter() works as expected:

```
sp1 = 'virginica'
filter(iris, Species == sp1)
```

But when I want to create a list based on the factor level **Species**, it fails

```
sp2 = levels(iris$Species)

lapply(sp2, function(x) {
  filter(iris, Species == x)
})
```

Same if factor is used as character variable:

```
sp3 = unique(as.character(iris$Species))

lapply(sp3, function(x) {
  filter(iris, Species == x)
})

```

When using with dplyr, it's working correctly:

```
lapply(sp2, function(x) {
  dplyr::filter(iris, Species == x)
})

lapply(sp3, function(x) {
  dplyr::filter(iris, Species == x)
})
```

**Comment by nathaneastwood** [comment]
Good spot, I'll take a look

**Comment by archymedes** [comment]
Same happens with the recent discoverted _tidyft_ package (althought data is a data.table). I saw the _rich man_ comment, and if you have something in common, you are having the same problem maybe. I have not noticed there yet

**Comment by nathaneastwood** [comment]
For now you can use

```r
split(iris, iris$Species)
```

But I will see if I can come up with something.
