### ISSUE TITLE
supporting older R versions

### ISSUE THREAD

**Issue by IndrajeetPatil** [nathaneastwood/poorman#94]
Recently, we switched from `{dplyr}` to `{poorman}` in all our packages, and it went smoothly!
So, first, thanks for this amazing contribution! 🙇‍♂️ 

The only thing that we found to be missing was support for `R 3.4`. `{dplyr}` currently supports all versions upwards of `R 3.3`, but `{poorman}` from `R 3.5`. 

So we were wondering if there is any possibility to also support these older versions? 

Thanks.

**Comment by nathaneastwood** [comment]
Hi @IndrajeetPatil. Thanks for the support. This shouldn’t be an issue at all. I’ll need to do some testing which I will try to get to over the weekend.

**Comment by nathaneastwood** [comment]
Out of curiosity, which packages are you using poorman in?

**Comment by IndrajeetPatil** [comment]
Awesome!

We are actually switching to `{poorman}` across our entire ecosystem. You can have a look at the individual packages here:
https://github.com/easystats

**Comment by nathaneastwood** [comment]
That's amazing!! I'll definitely take a look at this asap!

**Comment by bgilman-nyk** [comment]
+1
