### ISSUE TITLE
Support Embracing (curly curly operateror)

### ISSUE THREAD

**Issue by kalaschnik** [nathaneastwood/poorman#95]
Compare with tidyverse:
```r
library(tidyverse)
col_var <- "mpg"
mtcars %>% select({{ col_var }})
```

this does not work in `poorman`

**Comment by nathaneastwood** [comment]
I’m not sure it’s anything I want to support right now. Those operators are developed at the C level (I think) and that goes against the nature of poorman. I could in theory develop something to work at the R level but it would probably be very abstract and inefficient. Not to mention there are great NSE tools in base R already which I would encourage users to learn.

**Comment by Kalaschnik** [comment]
I get your point. Are you referring to `!!sym()`?

**Comment by nathaneastwood** [comment]
No, that's also rlang code. The base R equivalent would be functions that poorman takes advantage of such as bquote, eval, parse, substitute, etc. take a look at `poorman:::dotdotdot()`

**Comment by Kalaschnik** [comment]
Nice. Inspired by JavaScript’s spread operator?
